### ISSUE TITLE
"JetpackFallFix" by Hamunii causes ModelReplacementAPI to not work at all

### ISSUE THREAD

**Issue by rocketbuuny** [BunyaPineTree/LethalCompany_ModelReplacementAPI#100]
When JetpackFallFix mod is enabled, it prevents ModelReplacementAPI from changing models used when equipping a suit for unknown reason.
When JetpackFallFix is enabled, I look like this:
![image](https://github.com/Hamunii/JetpackFallFix/assets/140739502/d5622be5-b9ea-4e80-aba7-4ac2f5301ec6)

When JetpackFallFix is not enabled, ModelReplacementAPI works as expected and replaces the model like this:
![image](https://github.com/Hamunii/JetpackFallFix/assets/140739502/2eba79ac-5088-4768-b9a4-82e5f06459ed)

Using AFK emote from "TooManyEmotes" by FlipMods (v2.1.14) to go into third person

Using DragonBlack suit from "ThiccCompanyModelReplacement" (v2.0.1) by FoxGod to show ModelReplacementAPI breaking, but all other mods that have ModelReplacementAPI as a dependency also look broken

Also submitted this issue on the Github for JetpackFallFix by Hamunii [here](https://github.com/Hamunii/JetpackFallFix)

**Comment by BunyaPineTree** [comment]
Briefly looking at the source for JetPackFallFix, it looks like they patch the method I use as an entry point with an ILCursor instead of Harmony. I haven't exactly read up on how those two methods for patching interact, but I wouldn't be shocked if it wasn't well. Either way, I don't think this could be solved without drastic changes on either of our ends, so I would just take it to be an incompatibility for now.

**Comment by rocketbuuny** [comment]
ok, thanks for informing!
