### ISSUE TITLE
Can't figure out how to add glow or maps to models

### ISSUE THREAD

**Issue by MajorSanguine** [BunyaPineTree/LethalCompany_ModelReplacementAPI#102]
I'm fairly new to unity and all this, I can't figure out how to get a glow texture or map textures on my models. I tried emission for the glow which didn't work, using a normal map for my map didn't work either, nothing works except for albedo on standard shader. I know it's possible as I've seen models with glowing textures (like V1 and V2 models), not sure if the maps are possible though. Any pointers will be greatly appreciated
![a](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/168880831/073b67bf-384a-4286-afa9-ce0ac1a28844)
![aa](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/168880831/53ea1a28-78fe-4f9a-af7d-f25f365d72f7)
Example of the V1 model glowing. I want the eyes of the Dry Bones model to glow but can't figure it out

**Comment by BunyaPineTree** [comment]
Everything you can achieve in HDRP is possible. Perhaps you're missing a setting, or your emission texture isn't correct, but populating the emission map is the correct avenue. 

Regardless, this isn't really the place to ask about unity material mechanics. I would like to keep these issues exclusive to problems with the API.

**Comment by BunyaPineTree** [comment]
Actually, on second thought I can provide a pointer regarding how the API handles materials.

Make sure your materials utilize the HDRP Lit shader, or any other shader in the HDRP tree. 
If you are using the Standard shader, it will be converted to the base game shader automatically, and due to how shaders are written, it is only possible to convert the albedo map. 

The correct way to do this is to install High Definition RP in the package manager, or whatever it's called, in your unity project, if it isn't already HDRP enabled. To convert your Standard shader materials to HDRP, you need to use the HDRP wizard, which I cannot recall where in the menus it is right now.   

Anyways best of luck.

**Comment by MajorSanguine** [comment]
> Actually, on second thought I can provide a pointer regarding how the API handles materials.
> 
> Make sure your materials utilize the HDRP Lit shader, or any other shader in the HDRP tree. If you are using the Standard shader, it will be converted to the base game shader automatically, and due to how shaders are written, it is only possible to convert the albedo map.
> 
> The correct way to do this is to install High Definition RP in the package manager, or whatever it's called, in your unity project, if it isn't already HDRP enabled. To convert your Standard shader materials to HDRP, you need to use the HDRP wizard, which I cannot recall where in the menus it is right now.
> 
> Anyways best of luck.

I'm very sorry for the bother, I didn't know where else to ask. I finally figured it out though, it ended up being an unlit shader, the hdrp unlit just made my model black. Thank you for the response though, this has been fun to experiment with!
