### ISSUE TITLE
[2.3.1]Model Display Problems With MirrorDecor

### ISSUE THREAD

**Issue by XoF-eLtTiL** [BunyaPineTree/LethalCompany_ModelReplacementAPI#21]
# The following mods are mainly used
- [ModelReplacementAPI](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI)
- [PlayerAvatarLoader](https://github.com/NotAustinVT/LethalCompany_PlayerAvatarLoader)
- [MoreCompany](https://github.com/notnotnotswipez/MoreCompany)
- [Lethal-Company-More-Suits](https://github.com/x753/Lethal-Company-More-Suits)

# issues
- When using ohter suit that do not attach specific model, The default crew model will appear as shown in the picture.

# Current Situation
- Custom Model can normally load by changing Suit
- Synchronized model replacement works fine

# Question
- I'd like to know if it's a problem with PlayerAvatarLoader or ModelReplacementAPI.

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/78378322/80fec6d7-e82c-4f6f-8faa-88b2c41f2a80)

**Comment by BunyaPineTree** [comment]
I have installed the suggested mods, a third person mod, and a random model replacement to test against, though the behavior did not change when I removed the third person mod. 
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/5e8ed788-f272-4803-b3aa-bc3272ab199b)

Can you assure me that you are using the latest version of the API? This bug should have been fixed in recent releases. It is possible to be "unfixed" if you are using a mod that you didn't mention that changes the player camera's culling mask. 
Regardless, I was not able to recreate this bug. 
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/92621300-f88a-4518-b668-a843572482cf)

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/ee32b5a1-a794-48e2-89c6-332ce7f172b0)


![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/adf03104-c5f7-4d6f-ad64-4b6b61016199)

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/a28ec204-448e-4b8b-b028-afe05d203407)

**Comment by XoF-eLtTiL** [comment]
Hello. I've got a problem.
MirrorDecor

# Version 1.2.1
 - Fixed method of disabling the players' visors so that it only disables the shadows instead of the object itself

**Comment by XoF-eLtTiL** [comment]
Hello. I've got a problem.
MirrorDecor 1.2.1

**Comment by LEEJER** [comment]
I have the same problem as the original poster. To clarify OP's most recent comment: this issue occurs if [MirrorDecor by quackandcheese](https://thunderstore.io/c/lethal-company/p/quackandcheese/MirrorDecor/) is installed. 

In other words, when MirrorDecor is installed, basic texture-swapped suits do not work properly. Model-replaced suits work fine.

**Comment by BunyaPineTree** [comment]
Thanks for the report. This has already been fixed and will be put out on the next update with a few other fixes.
