### ISSUE TITLE
[Idea] Register monsters models

### ISSUE THREAD

**Issue by Edouard127** [BunyaPineTree/LethalCompany_ModelReplacementAPI#42]
I assume that the monsters have the same hierarchy as the player controller when it comes to the body
So It would be easy, create a list of RegisteredMonsterModels
Create a RegisterMonsterModel that takes the type of the monster and the type of the model
And voila

**Comment by Edouard127** [comment]
Actually It may take more code, looking into EnemyAI, there is an array of skinned mesh renderer
Maybe we can get the component like with the player ?

**Comment by BunyaPineTree** [comment]
It's true that almost everything we do in the regular body replacement applies to all model replacements in general, and if you've noticed, PlayerControllerB is used almost exclusively for first person changes and LODS, which aren't necessary for monsters. 
The issue is that monsters aren't necessarily humanoid, and we will need to find a generalized way to encode armatures to and from the monster armatures. 
The way we achieve this with players is with the humanoid avatar. It's possible that we can achieve some kind of jank with humanoid avatars to achieve similar results, but the number of monster specific patches we would need is a workload I can't do right now. 
If you want to try this yourself, I can give you a few guidelines to work with from my own ruminations on the topic.

**Comment by Edouard127** [comment]
At least we can replace the coil-head and the bracken as they are humanoid, right?

**Comment by BunyaPineTree** [comment]
I don't have the time to work on that right now, but you or anyone else are more than free to.

**Comment by BunyaPineTree** [comment]
After working out masked, I realized there were already lots of enemy replacement mods out there, so an API isn't really needed.
