### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by alekso56** [BunyaPineTree/LethalCompany_ModelReplacementAPI#43]
Hello, 
I was wondering if it would be possible to add support for a third party website to load models,
i created a fork here https://github.com/alekso56/LethalCompany_ModelReplacementAPI
to load models at runtime.
with a website using S3/MINIO to download/upload avatars here: https://lethal.cax.no/
api doc: https://lethal.cax.no/swagger/index.html

auth for upload is handled using steam login.

workflow 
create avatar in unity using sdk -> upload assetbundle to website -> immediatly loads ingame.

also another idea is compatability with the upcoming vr mod here: https://github.com/DaXcess/LCVR

i just wanted your opinions on this stuff.  😄

**Comment by BunyaPineTree** [comment]
First of all I'm glad you're using assetbundles, instead of dlls for security reasons. 
I don't intend on adding steam id support right now as a matter of scope, however it sounds like what you want to achieve has already been done in part by NotAustin here. 
https://github.com/NotAustinVT/LethalCompany_PlayerAvatarLoader
If you would like I can get into touch with NotAustin in proposing your idea.

Regarding VR support, I'm not sure why it wouldn't be supported by base, but as someone who does not own a VR headset I wouldn't be able to test it to begin with.

**Comment by alekso56** [comment]
thank you for responding.
