### ISSUE TITLE
Need help with the physics

### ISSUE THREAD

**Issue by StrikingPopcorn** [BunyaPineTree/LethalCompany_ModelReplacementAPI#52]
Hey,
I'm new to this and am therefore still learning the ropes and I have managed to implement a custom model, it loads in the game and everything, but I just can't figure out how to get the physics to work, I tried spring Bones, Dynamic Bones, and the included Jiggle Physics and nothing worked. They always work fine within the Unity editor but are nonexistent in the game. And the documentation doesn't give any sort of info on how to use them.
I would be extremely thankful for any sort of tutorial or explanation on how to implement the physics.

Greetings,
StrikingPopcorn

**Comment by Edouard127** [comment]
I can't help you with how to do it but I can redirect you to the custom physics implementation 

https://github.com/naelstrof/UnityJigglePhysics

**Comment by BunyaPineTree** [comment]
Historically, UnityJigglePhysics related issues have always been a result of people importing the primary UnityJigglePhysics package into their unity project. Even if you remove the package and use the scripts in the SDK, this has still been an issue.
It could also be due to an outdated API.dll that you are building your mod with, or are using in your bepinex plugins folder, but that shouldn't be very likely due to how outdated it would need to be. 

Besides that, if you don't want to use UnityJigglePhysics as supplied in the SDK, you'll have to mess around with Assembly Definitions which is a real pain, and not something I would recommend.

**Comment by StrikingPopcorn** [comment]
So, I have never imported the primary UnityJigglePhysics, I've only used the scripts in the SDK, besides the Spring Bone and Dynamic Bone tests of course. I've now even created a brand new 3D HDRP Unity Project and only imported the SDK. And again the after adding the Jiggle Rig Builder, settings for it etc. The physics did work inside the Unity Editor, so I exported everything using the Project thingy from the SDK and compiled it in Visual Studio put it into the game. The model loaded just as it should but again, had no physics whatsoever.

Maybe I'm missing something in the code, or I am placing the Rig Builder in the wrong part of the Hierarchy or maybe the model is just incompatible due to the way it is set up or something. I am completely confused and have already spent somewhere around a day just trying different things.

**Comment by BunyaPineTree** [comment]
If you've confirmed that those two possibilities are not the issue, then there is unfortunately no way for me to help you. The physics using specifically the SDK scripts have worked every time I have used them. If they aren't working for you, I wouldn't have any idea how, as I did not write the scripts themselves. Perhaps contact Naelstrof at the UnityJigglePhysics github.
