### ISSUE TITLE
default suits go invisible on death

### ISSUE THREAD

**Issue by PeachCake314** [BunyaPineTree/LethalCompany_ModelReplacementAPI#53]
only the default suits go invisible, modded models are fine. the console log says "Setting linear velocity of a kinematic body is not supported."

**Comment by BunyaPineTree** [comment]
Thanks for the report. Did this result from a combination of mods, or were you only using modelreplacementAPI?

**Comment by PeachCake314** [comment]
I'm using other mods, I can try testing with just this mod installed later today

**Comment by SylviBlossom** [comment]
I did decide to personally test this with only this mod installed, and it does seem like the issue happens on its own:
![screen-018907](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89804482/8ff8eaa1-abfb-4ce3-9d4b-6e268f7c064e)
And weirdly spectators can see all dead bodies, only living players can't.

**Comment by Edouard127** [comment]
Is there anything in the logs you can provide ?

**Comment by SylviBlossom** [comment]
> Is there anything in the logs you can provide ?

Doesn't seem like anything is out of ordinary in the logs, there is a warning on death ("Setting linear velocity of a kinematic body is not supported.") but I'm pretty sure that appears in vanilla
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89804482/49588c8e-8b5e-498f-a746-f189d8464f25)

**Comment by BunyaPineTree** [comment]
Thanks for the highly detailed testing. I don't know where this issue came from, as ragdolls are instantiated from a list of prefabs rather than cloned from the dead player, their layers shouldn't be affected. 
Regardless, it seems that the issue is the ragdolls being set to the model layer which isn't visible in first person. I don't have the time to correct this right now, but on my next update I will see about it being fixed.
