### ISSUE TITLE
Jiggle physics makes my character move on its own

### ISSUE THREAD

**Issue by aki-cat** [BunyaPineTree/LethalCompany_ModelReplacementAPI#59]
I'm struggling to debug the jiggle physics component. I added it to my characters' tail and configured it to flow just the way I wanted. It worked fine on editor, but when I tested it in-game, my character started moving on its own and flying around.

I'm assuming, possibly wrongly, that the colliders might be causing it. Is there any specific way one should configure colliders so this does not happen?

Finally, is there some documentation on how the jiggle physics is to be properly configured?

(This project is incredible and I'm having a blast with it btw, so thanks for doing this and making it available!)

**Comment by BunyaPineTree** [comment]
Your specific issue can probably be fixed by setting your colliders to `isTrigger` in the inspector window.   

Besides that, any questions specifically regarding jiggle physics configurations should be asked about [here](https://github.com/naelstrof/UnityJigglePhysics), as it is entirely separate from my project. You may also simply find your answers on the ReadMe page.

**Comment by aki-cat** [comment]
Thank you. I went back to the README and saw the mention of the UnityJigglePhysics project. I shall close this issue then.
