### ISSUE TITLE
Issue with First Person View of Model

### ISSUE THREAD

**Issue by coltongraham99** [BunyaPineTree/LethalCompany_ModelReplacementAPI#69]
I am attempting to import a player model using your mod tool, however, the first person view appears to be bugged. I think perhaps the camera is clipped into the model, but I'm not sure, as all I can see if a solid color screen (see attached photo). The model appears to be importing correctly as it looks correct in third person using a separate third person view mod (see second attached photo). I have attempted to shrink and squash the model to resolve this but have had no luck. Mostly likely this is user error on my part, but I'm not sure how to resolve it and in case not I thought I would report the possible issue.

 The tutorial does not mention where the person camera is placed relative to the bone structure of the model, could you elaborate on that? Perhaps I need to move the position of the head bone relative to the model? I do not believe I have skipped anything in your instructions. I apologize if I have made some obvious error, I have very minimal experience with using unity. Thank you for your help in resolving this issue, and for making this amazing mod tool!

![firstperson](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/44416457/9b88fdc7-3ea8-4d1b-be38-e8693bafe380)
![thirdperson](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/44416457/3e50d58e-0dd4-4246-bf9e-f6a52146db95)

**Comment by BunyaPineTree** [comment]
This issue is covered in the FAQ on the wiki. You have a camera somewhere on your model that is taking focus from the firstperson camera, and it needs to be either removed or disabled. 

As a purely cosmetic mod, I don't have any intentions of adding a functionality to change the position of the camera, or anything that would modify your experience of the game unfairly. That would also be a nightmare for compatibility.

**Comment by coltongraham99** [comment]
Ah, sorry. That resolved the issue, thank you for your help!
